# SPDX-License-Identifier: Apache-2.0
# © Crown Copyright 2025. This work has been developed by the National Digital Twin Programme and is legally attributed to the Department for Business and Trade (UK) as the governing entity.

name: Publish to GHCR

on:
  push:
    branches:
      - main

jobs:
  verify:
    name: Verify the release code
    runs-on: ubuntu-latest
    outputs:
      version: ${{ steps.get-version.outputs.version }}
    env:
      MAVEN_CLI_OPTS: "--batch-mode --no-transfer-progress"
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Setup Java/Maven
        uses: actions/setup-java@v5
        with:
          java-version: 21
          distribution: "temurin"
          cache: maven
      - name: Test
        run: mvn $MAVEN_CLI_OPTS verify
      - name: Get version
        id: get-version
        run: echo version=$(./mvnw $MAVEN_CLI_OPTS help:evaluate -Dexpression=project.version -q -DforceStdout) >> $GITHUB_OUTPUT

  publish:
    name: Publish the release to GHCR
    needs: verify
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
      id-token: write
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Get repo name
        id: get-repo
        run: echo "docker_repo=${GITHUB_REPOSITORY,,}" >> $GITHUB_OUTPUT
      - name: Login to ghcr.io
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Build docker image
        run: |
          docker build \
          --tag ghcr.io/${{ steps.get-repo.outputs.docker_repo }}:${{ needs.verify.outputs.version }} \
          --tag ghcr.io/${{ steps.get-repo.outputs.docker_repo }}:latest \
          --label org.opencontainers.image.created=$(date -u +%Y-%m-%dT%H:%M:%SZ) \
          -f Dockerfile .
      - name: Publish docker image
        run: |
          docker push ghcr.io/${{ steps.get-repo.outputs.docker_repo }}:${{ needs.verify.outputs.version }}
          docker push ghcr.io/${{ steps.get-repo.outputs.docker_repo }}:latest
